import { Link } from 'react-router-dom'

const PROSE = `
  .legal-h2 {
    font-family: 'Plus Jakarta Sans', system-ui;
    font-size: 20px;
    font-weight: 700;
    color: #0f172a;
    margin: 36px 0 10px;
  }
  .legal-p {
    font-size: 16px;
    color: #374151;
    line-height: 1.75;
    margin: 0 0 12px;
  }
  .legal-ul {
    margin: 0 0 12px;
    padding-left: 20px;
  }
  .legal-ul li {
    font-size: 16px;
    color: #374151;
    line-height: 1.75;
    margin-bottom: 4px;
  }
`

export default function TermsOfService() {
  return (
    <div style={{ minHeight: '100vh', background: '#f8fafc' }}>
      <style>{PROSE}</style>

      {/* Top nav */}
      <div style={{ background: 'white', borderBottom: '1px solid #e2e8f0', padding: '16px 24px' }}>
        <div style={{ maxWidth: 800, margin: '0 auto', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Link to="/" style={{ fontFamily: "'Plus Jakarta Sans', system-ui", fontSize: 22, fontWeight: 800, color: '#0f172a', textDecoration: 'none', letterSpacing: '-0.5px' }}>
            Praisly
          </Link>
          <Link to="/" style={{ fontSize: 14, color: '#64748b', textDecoration: 'none' }}>← Back to home</Link>
        </div>
      </div>

      {/* Content */}
      <div style={{ maxWidth: 800, margin: '0 auto', padding: '48px 24px 80px' }}>
        <h1 style={{ fontFamily: "'Plus Jakarta Sans', system-ui", fontSize: 32, fontWeight: 800, color: '#0f172a', margin: '0 0 8px' }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: 14, color: '#94a3b8', marginBottom: 40 }}>Last updated: May 2026</p>

        <p className="legal-p">
          These terms apply to your use of Praisly (praisly.in). By creating an account, you agree to these terms. If you do not agree, do not use the service.
        </p>

        <h2 className="legal-h2">What Praisly does</h2>
        <p className="legal-p">
          Praisly is an AI-powered review collection tool that helps Indian local businesses collect genuine Google reviews from their customers. It sends review requests via WhatsApp, generates AI-drafted review suggestions, and tracks your Google rating over time.
        </p>

        <h2 className="legal-h2">Your account</h2>
        <ul className="legal-ul">
          <li>You are responsible for keeping your account credentials secure.</li>
          <li>One account per business. You must be the owner or an authorised representative of the business.</li>
          <li>You must provide accurate business information during signup.</li>
        </ul>

        <h2 className="legal-h2">Acceptable use</h2>
        <p className="legal-p">You agree not to use Praisly to:</p>
        <ul className="legal-ul">
          <li>Solicit fake or incentivised reviews (this violates Google's policies)</li>
          <li>Send unsolicited spam to people who are not your customers</li>
          <li>Harass, threaten, or deceive customers</li>
          <li>Attempt to access other businesses' data</li>
          <li>Use the service for any illegal activity under Indian law</li>
        </ul>
        <p className="legal-p">
          We reserve the right to suspend or terminate accounts that violate these terms without notice.
        </p>

        <h2 className="legal-h2">AI-generated content</h2>
        <p className="legal-p">
          Praisly generates review draft suggestions using AI. These are suggestions only — your customer chooses whether to post, edit, or discard them. Praisly is not responsible for the content customers choose to post on Google. Review text generated by AI may not always be accurate or reflect your business perfectly.
        </p>

        <h2 className="legal-h2">Free trial</h2>
        <p className="legal-p">
          New accounts get a 7-day free trial with full access to all features. No credit card is required to start. The trial expires automatically after 7 days. After expiry, you will need a paid subscription to continue collecting reviews.
        </p>

        <h2 className="legal-h2">Payments and subscriptions</h2>
        <ul className="legal-ul">
          <li>Subscriptions are billed monthly (₹999/month) or yearly (₹7,999/year).</li>
          <li>Payments are processed by Razorpay. By subscribing you also agree to Razorpay's terms.</li>
          <li>You can cancel your subscription at any time. You will retain access until the end of your current billing period.</li>
          <li>We do not offer refunds for partial billing periods, but you may request one by emailing us and we will review it case by case.</li>
        </ul>

        <h2 className="legal-h2">Service availability</h2>
        <p className="legal-p">
          We aim for high availability but cannot guarantee uninterrupted service. Praisly is provided "as is." We do not guarantee any specific number of Google reviews, improvement in your Google rating, or ranking in search results. Results depend on many factors outside our control.
        </p>

        <h2 className="legal-h2">Limitation of liability</h2>
        <p className="legal-p">
          To the maximum extent permitted by law, Praisly's liability for any claim arising from your use of the service is limited to the amount you paid in the 3 months before the claim. We are not liable for indirect, incidental, or consequential damages.
        </p>

        <h2 className="legal-h2">Changes to these terms</h2>
        <p className="legal-p">
          We may update these terms from time to time. We will notify you by email if we make significant changes. Continued use of the service after changes means you accept the updated terms.
        </p>

        <h2 className="legal-h2">Governing law</h2>
        <p className="legal-p">
          These terms are governed by the laws of India. Any disputes will be subject to the jurisdiction of courts in India.
        </p>

        <h2 className="legal-h2">Contact</h2>
        <p className="legal-p">
          Questions or disputes? Email us at <a href="mailto:support@praisly.in" style={{ color: '#10b981' }}>support@praisly.in</a>.
          <br />
          Praisly is operated by Rahul Kumar, India.
        </p>
      </div>

      {/* Footer */}
      <div style={{ background: '#f1f5f9', borderTop: '1px solid #e2e8f0', padding: '20px 24px', textAlign: 'center' }}>
        <p style={{ fontSize: 13, color: '#94a3b8', margin: 0 }}>
          © 2026 Praisly · <Link to="/privacy" style={{ color: '#64748b', textDecoration: 'none' }}>Privacy Policy</Link>
        </p>
      </div>
    </div>
  )
}
